name: moviesquare
version: git
summary: GUI for Browsing and Discovering new Movies
description: |
  MovieSquare showcases popular movies from around the world and help you in discovering new movies by settings deifferent filtering criterias.
  
grade: stable
confinement: strict
icon: snap/gui/icon.png
base: core20
compression : lzo

architectures:
  - build-on: amd64
    run-on: amd64

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/qt5-core20

apps:
  moviesquare:
    command: bin/desktop-launch $SNAP/usr/bin/moviesquare
    environment:
       DISABLE_WAYLAND: 1
       IS_SNAP: 1
    desktop: usr/share/applications/moviesquare.desktop
    plugs:
        - home
        - unity7
        - network
        - opengl
        - x11
        - alsa
        - audio-playback
        - desktop
        - gsettings
        - wayland
        - desktop-legacy
plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt5-core20:
    interface: content
    target: $SNAP/qt5-core20
    default-provider: qt5-core20

parts:
   desktop-qt5-build:
     plugin: nil
     build-packages:
       - build-essential
       - qtbase5-dev
       - dpkg-dev
       
   build-src:
     source: https://github.com/keshavbhatt/moviesquare.git
     source-subdir: src/
     plugin: qmake
     after: [desktop-qt5-build]
     stage-packages:
          - fonts-tlwg-typewriter
     override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/src/moviesquare.desktop
            
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
            cp -rf ${SNAPCRAFT_PART_SRC}/src/moviesquare.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/moviesquare.desktop

   desktop-launch:
     plugin: nil
     source: https://github.com/keshavbhatt/qt5-core20.git
     after: [build-src]
     override-build: |
            snapcraftctl build
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
            cp -rf ${SNAPCRAFT_PART_SRC}/snap_launcher/bin/desktop-launch ${SNAPCRAFT_PART_INSTALL}/bin/
